import { Router } from 'express';
import { requireAuth } from '../middleware/requireAuth';
import authRoutes from '../modules/auth/auth.routes';
import analyticsRoutes from '../modules/analytics/analytics.routes';
import activityLogRoutes from '../modules/activityLogs/activityLog.routes';
import departmentRoutes from '../modules/departments/department.routes';
import categoryRoutes from '../modules/categories/category.routes';
import assetRoutes from '../modules/assets/asset.routes';
import allocationRoutes, { transferRouter } from '../modules/allocations/allocation.routes';
import bookingRoutes from '../modules/bookings/booking.routes';
import maintenanceRoutes from '../modules/maintenance/maintenance.routes';
import auditRoutes from '../modules/audits/audit.routes';
import userRoutes from '../modules/users/user.routes';

const router = Router();
router.use('/auth', authRoutes);
router.use(requireAuth);
router.use('/analytics', analyticsRoutes);
router.use('/activity-logs', activityLogRoutes);
router.use('/departments', departmentRoutes);
router.use('/categories', categoryRoutes);
router.use('/assets', assetRoutes);
router.use('/allocations', allocationRoutes);
router.use('/transfers', transferRouter);
router.use('/bookings', bookingRoutes);
router.use('/maintenance', maintenanceRoutes);
router.use('/audits', auditRoutes);
router.use('/users', userRoutes);
export default router;
